db:
  image: postgres:9.6.3
  environment:
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_DB=dev
  ports:
    - 5432:5432
  volumes:
    - ./db_data:/var/lib/postgresql/data

app_python:
  build: .
  dockerfile: DockerfileConda
  command: python /app/app.py
  hostname: app_python
  links:
    - db
  volumes:
    - ./app:/app
    - ./data:/data
